import React, { useState } from 'react'
import Head from 'next/head'

const EditUser = () => {
  const [ID, setID] = useState('')
  const [role, setRole] = useState('')
  const [message, setMessage] = useState('')

  let handleSubmit = async (e: { preventDefault: () => void }) => {
    e.preventDefault()
    try {
      let res = await fetch(`https://butq3lt5uk.execute-api.eu-west-2.amazonaws.com/stage/users/${ID}/roles`, {
        method: 'POST',
        headers: {
          Accept: 'application/json',
          'Content-Type': 'application/json',
        },
        body: role,
      })
      let resJson = await res.json()
      if (res.status === 201) {
        setID('')
        setMessage('User add to the group successfully')
      } else {
        setMessage('Some error occurred')
      }
    } catch (err) {
      console.log(err)
    }
  }
  return (
    <div>
      <Head>
        <title>User Management</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <h1 id="title">Assign Role To User</h1>
        </div>

        <br></br>

        <div style={{ display: 'flex', justifyContent: 'center' }}>
          <form onSubmit={handleSubmit}>
            <p>Input ID of the user</p>
            <br></br>
            <input
              type="text"
              value={ID}
              placeholder="ID"
              onChange={(e) => setID(e.target.value)}
            />
            <br></br>

            <p>Input the group name you want to add the user</p>
            <br></br>
            <input
              type="text"
              value={role}
              placeholder="Name"
              onChange={(e) => setRole(e.target.value)}
            />
            <br></br>

            <button type="submit" style={{ backgroundColor: '#F9A825' }}>
              Assign Role To User
            </button>

            <div className="message">{message ? <p>{message}</p> : null}</div>
          </form>
        </div>

      </main>
    </div>
  )
}

export default EditUser
