import React, { useState } from 'react'
import Head from 'next/head'

const EditUser = () => {
  const [name, setName] = useState('')
  const [ID, setID] = useState('')
  const [email, setEmail] = useState('')
  const [phone, setPhone] = useState('')
  const [address, setAddress] = useState('')
  const [message, setMessage] = useState('')

  let handleSubmit = async (e: { preventDefault: () => void }) => {
    e.preventDefault()
    try {
      let res = await fetch(`https://butq3lt5uk.execute-api.eu-west-2.amazonaws.com/stage/users/${ID}`, {
        method: 'PUT',
        headers: {
          Accept: 'application/json',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          name: name,
          email: email,
          phone: phone,
          address: address,
        }),
      })
      let resJson = await res.json()
      if (res.status === 201) {
        setName('')
        setEmail('')
        setID('')
        setPhone('')
        setAddress('')
        setMessage('User updated successfully')
      } else {
        setMessage('Some error occurred')
      }
    } catch (err) {
      console.log(err)
    }
  }
  return (
    <div>
      <Head>
        <title>User Management</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <h1 id="title">Edit User</h1>
        </div>

        <br></br>

        <div style={{ display: 'flex', justifyContent: 'center' }}>
          <form onSubmit={handleSubmit}>
            <p>Input ID and the Email of the user</p>
            <br></br>
            <input
              type="text"
              value={ID}
              placeholder="ID"
              onChange={(e) => setID(e.target.value)}
            />
            <input
              type="text"
              value={email}
              placeholder="Email"
              onChange={(e) => setEmail(e.target.value)}
            />
            <br></br>

            <p>Input New User data and submit</p>
            <br></br>
            <input
              type="text"
              value={name}
              placeholder="Name"
              onChange={(e) => setName(e.target.value)}
            />
            <input
              type="text"
              value={phone}
              placeholder="Phone"
              onChange={(e) => setPhone(e.target.value)}
            />
            <input
              type="text"
              value={address}
              placeholder="Address"
              onChange={(e) => setAddress(e.target.value)}
            />

            <br></br>

            <button type="submit" style={{ backgroundColor: '#F9A825' }}>
              Update User
            </button>

            <div className="message">{message ? <p>{message}</p> : null}</div>
          </form>
        </div>
      </main>
    </div>
  )
}

export default EditUser
