import React, { useState } from 'react'
import Head from 'next/head'

const SearchUser = () => {
  const [ID, setID] = useState('')
  const [message, setMessage] = useState('')
  const [user, setUser] = useState({})
  const [name, setName] = useState('')
  const [email, setEmail] = useState('')
  const [phone, setPhone] = useState('')
  const [address, setAddress] = useState('')

  let handleSubmit = async (e: { preventDefault: () => void }) => {
    e.preventDefault()
    try {
      let res = await fetch(`https://butq3lt5uk.execute-api.eu-west-2.amazonaws.com/stage/users/${ID}`, {
        method: 'GET',
        headers: {
          Accept: 'application/json',
          'Content-Type': 'application/json',
        },
      })
      let resJson = await res.json()

      if (res.status === 200) {
        setID('')
        setMessage('User found successfully')
        console.log(resJson.data.data)
        setUser(resJson.data.data);
        setName(resJson.data.data.name);
        setEmail(resJson.data.data.email);
        setPhone(resJson.data.data.phone);
        setAddress(resJson.data.data.address);
        
      } else {
        setMessage('Some error occurred')
      }
    } catch (err) {
      console.log(err)
    }
  }
  return (
    <div>
      <Head>
        <title>User Management</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <h1 id="title">Search User</h1>
        </div>

        <br></br>

        <div style={{ display: 'flex', justifyContent: 'center' }}>
          <form onSubmit={handleSubmit}>
            <p>Input ID of the user you want to search</p>
            <br></br>
            <input
              type="text"
              value={ID}
              placeholder="ID"
              onChange={(e) => setID(e.target.value)}
            />

            <br></br>

            <button type="submit" style={{ backgroundColor: '#2196F3' }}>
              Search User
            </button>

            <div className="message">{message ? <p>{message}</p> : null}</div>
          </form>

        </div>

        <br></br>

        <div className="user-details-container">
          {/* {user.id && <p style={{ display: 'flex', justifyContent: 'center'}}>ID: {user.id}</p>} */}
          {name && <p style={{ display: 'flex', justifyContent: 'center'}}>Name: {name}</p>}
          {email && <p style={{ display: 'flex', justifyContent: 'center'}}>Email: {email}</p>}
          {phone && <p style={{ display: 'flex', justifyContent: 'center'}}>Phone: {phone}</p>}
          {address && <p style={{ display: 'flex', justifyContent: 'center'}}>Address: {address}</p>}
        </div>

      </main>
    </div>
  )
}

export default SearchUser
