import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>User Management</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <div>
          <h1 id="title">Smart DB User Management Admin Portal</h1>
        </div>
      </main>
    </div>
  )
}
